#repo config
path_to_data: "/Users/toucanfirm/Documents/Zibra/dev/Cortrium/lead_gen/data/incart/physionet.org/files/incartdb/1.0.0"
#model parameters
s_freq: 257
channel_map: [0,1,2]
window_size: 30
hop: 20

#training parameters
batch_size: 32
learning_rate: 0.0001 #10e-5
n_epochs: 200